### ISSUE TITLE
Suggestion to add new Syncthing package Synology NAS repository

### ISSUE THREAD

**Issue by lordvandal** [szyb/synopackage_dotnet#128]
**Syncthing**
- Announcement of the author: [https://forum.syncthing.net/t/new-package-for-synology-nas/14396](https://forum.syncthing.net/t/new-package-for-synology-nas/14396)
- Instructions and package source here: [https://docs.kastelo.net/synology/](https://docs.kastelo.net/synology/)
- Package source: [https://synology.kastelo.net/](https://synology.kastelo.net/)
- GitHub repository: [https://github.com/kastelo/syncthing-synology](https://github.com/kastelo/syncthing-synology)

**Beatifica Bytes**
- Web site: [https://www.beatificabytes.be/](https://www.beatificabytes.be/)
- Package source: [https://www.beatificabytes.be/sspks/](https://www.beatificabytes.be/sspks/)

**Comment by szyb** [comment]
Hi @lordvandal ,

Thank you for reporting that. After a short investigation I see that Syncthing package is on the synocommunity repository as well as in the package center on my NAS, but it is not visible via search. I'll try to find out why (as time permits).

I'll also try to add new source to the search engine (https://www.beatificabytes.be/sspks/). Thanks for letting me know. 

BR,
Szymon

**Comment by szyb** [comment]
Hi,
New source Beatificabytes is available in the search engine at: https://search.synopackage.com/sources/beatificabytes

@lordvandal thank you for submission!

**Comment by szyb** [comment]
Hi @lordvandal ,

I looked at this closer and I don't think I can do more than I already did (add new source repository beatificabytes).
The Syncthing package is showing well in the search engine as long as synocommunity works, who is responsible for that package. So if you want to upgrade the package to the newest version you should contact them directly (probably the best way is to create issue here: https://github.com/SynoCommunity/spksrc/issues).

If you need more assistance from synopackage, please let me know. Otherwise I will close this issue.

**Comment by lordvandal** [comment]
Hi @szyb,

Thanks for the quick reply and implementation.
I find your work really useful and I like it, and I’m sure that many others too.
Keep up the good work!

**Comment by szyb** [comment]
Thank you for your feedback :)
